config/routes.rb
Rails.application.routes.draw do
resources :kittens
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "kittens#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, :age, :cuteness, :softness, presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all

    respond_to do |f|
      f.html
      f.xml { render xml: @kittens }
      f.json { render json: @kittens }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kit_params)
    if @kitten.save
      flash[:success] = 'Kitten created Successfully.'
      redirect_to @kitten      
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def show
    @kitten = Kitten.find(params[:id])
    respond_to do |f|
      f.html
      f.xml { render xml: @kitten }
      f.json { render json: @kitten }
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    kitten = Kitten.find(params[:id])
    kitten.update!(kit_params)
    redirect_to kitten
    flash[:success] = 'Kitten successfully updates.'
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    if @kitten.destroy
      redirect_to kittens_path
      flash[:success] = 'Kitten successfully destroyed.'
    else
      redirect_back(fallback_location: root_path)
      flash[:error] = 'Failed to destroy kitten.'
    end
  end

  private

  def kit_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= simple_form_for @kitten do |f| %>
  <%= f.input :name %>
  <%= f.input :age %>
  <%= f.input :cuteness %>
  <%= f.input :softness %>
  <%= f.button :submit %>
  <% end %>

app/views/kittens/create.html.erb
<h1>Kittens#create</h1>
<p>Find me in app/views/kittens/create.html.erb</p>

app/views/kittens/destroy.html.erb
<h1>Kittens#destroy</h1>
<p>Find me in app/views/kittens/destroy.html.erb</p>

app/views/kittens/edit.html.erb
<h1>Kittens#edit</h1>
<%= render "form" %>
<%= button_to 'Delete', kitten_path(@kitten), form: { data: { turbo_confirm: "Are you sure?" } }, method: :delete %>

app/views/kittens/index.html.erb
    <% flash.each do |type, msg| %>
      <div>
        <%= msg %>
      </div>
    <% end %>
    

<%= link_to "Create new Kitty", new_kitten_path %>
<h1>Kittens</h1>
<% @kittens.each do |kitten| %>
  <p>Name: <%= kitten.name %><br>
    <%= link_to "Show", kitten_path(kitten.id) %>
    <%= button_to "Delete", kitten_path(kitten), form: { data: { turbo_confirm: "Are you sure?" } }, method: :delete %>
  </p>
<% end %>

app/views/kittens/new.html.erb
<h1>Kittens#new</h1>
<%= render "form" %>

app/views/kittens/show.html.erb
<h2><%= @kitten.name %></h2>
<p>Age: <%= @kitten.age %></p>
<p>Cuteness: <%= @kitten.cuteness %></p>
<p>Softness: <%= @kitten.softness %></p>
<p><%= link_to 'Edit', edit_kitten_path %></p>
<p><%= link_to 'Home', kittens_path %></p>
<%= button_to 'Delete', kitten_path(@kitten), form: { data: { turbo_confirm: "Are you sure?" } }, method: :delete %>

app/views/kittens/update.html.erb
<h1>Kittens#update</h1>
<p>Find me in app/views/kittens/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Odin Kittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div>
        <%= msg %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>